TERMUX_PKG_HOMEPAGE=https://wiki.termux.com/wiki/Termux:API
TERMUX_PKG_DESCRIPTION="Termux API commands (install also the Termux:API app)"
TERMUX_PKG_LICENSE="MIT"
TERMUX_PKG_MAINTAINER="@termux"
TERMUX_PKG_VERSION=0.59.1
TERMUX_PKG_REVISION=2
TERMUX_PKG_SRCURL=https://github.com/PickleHik3/termux-api-package/archive/2e7f8e2.tar.gz
TERMUX_PKG_SHA256=7ad76a1aae610fc81f975ae3429b077808fcbc9c184fd5e2c78c58e5d0639a53
TERMUX_PKG_BUILD_IN_SRC=true
TERMUX_PKG_DEPENDS="bash, util-linux, termux-am (>= 0.8.0)"
TERMUX_PKG_EXTRA_CONFIGURE_ARGS="
-DCMAKE_POLICY_VERSION_MINIMUM=3.5
-DPREFIX=${TERMUX_PREFIX}
-DTERMUX_API_APP_PACKAGE_NAME=${TERMUX_APP__PACKAGE_NAME}.api
-DTERMUX_API_APP_JAVA_NAMESPACE=com.termux.api
-DLISTEN_SOCKET_ADDRESS=${TERMUX_APP__PACKAGE_NAME}.api://listen
-DTERMUX_API_COMPONENT=${TERMUX_APP__PACKAGE_NAME}.api/com.termux.api.TermuxApiReceiver
-DTERMUX_API_SERVICE_COMPONENT=${TERMUX_APP__PACKAGE_NAME}.api/com.termux.api.KeepAliveService
"
